In [1]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt 
import seaborn as sns 

In [2]:
df = pd.read_csv("final data.csv")

In [3]:
df

number  incidentstate  active  reassignmentcount  reopencount  \
0            0              7       1                  0            0   
1            0              1       1                  1            0   
2            0              1       1                  1            0   
3            0              1       1                  1            0   
4            0              1       1                  1            0   
...        ...            ...     ...                ...          ...   
141703   24915              6       0                  1            0   
141704   24916              1       1                  0            0   
141705   24916              1       1                  1            0   
141706   24916              8       1                  1            0   
141707   24916              6       0                  1            0   

        sysmodcount  contact_type  knowledge  upriorityconfirmation  \
0                 0             3          1                      0   
1                 1             3          1                      0   
2                 2             3          1                      0   
3                 3             3          1                      0   
4                 4             3          1                      0   
...             ...           ...        ...                    ...   
141703            4             1          0                      1   
141704            0             1          0                      0   
141705            1             1          0                      0   
141706            2             1          0                      1   
141707            3             1          0                      1   

        caller_id  ...  opened_at_day  opened_at_month  opened_at_year  \
0            2403  ...             29                2            2016   
1            2403  ...             29                2            2016   
2            2403  ...             29                2            2016   
3            2403  ...             29                2            2016   
4            2403  ...             29                2            2016   
...           ...  ...            ...              ...             ...   
141703        116  ...             16                2            2017   
141704        116  ...             16                2            2017   
141705        116  ...             16                2            2017   
141706        116  ...             16                2            2017   
141707        116  ...             16                2            2017   

        opened_at_hr  opened_at_minute  created_at_day  created_at_month  \
0                  4                40              29                 2   
1                  4                40              29                 2   
2                  4                40              29                 2   
3                  4                40              29                 2   
4                  4                40              29                 2   
...              ...               ...             ...               ...   
141703             9                 9              27                 1   
141704            14                17              27                 1   
141705            14                17              27                 1   
141706            14                17              27                 1   
141707            14                17              27                 1   

        created_at_year  created_at_hr  created_at_minute  
0                  2016              4                 57  
1                  2016              4                 57  
2                  2016              4                 57  
3                  2016              4                 57  
4                  2016              4                 57  
...                 ...            ...                ...  
141703             2017             16                 5

In [4]:
df.isnull().sum()

number                   0
incidentstate            0
active                   0
reassignmentcount        0
reopencount              0
sysmodcount              0
contact_type             0
knowledge                0
upriorityconfirmation    0
caller_id                0
open_by                  0
createdby                0
updatedby                0
loc                      0
category                 0
symptom                  0
i_impact                 0
assigned_to              0
updated_day              0
updated_month            0
updated_year             0
updated_hr               0
updated_minute           0
opened_at_day            0
opened_at_month          0
opened_at_year           0
opened_at_hr             0
opened_at_minute         0
created_at_day           0
created_at_month         0
created_at_year          0
created_at_hr            0
created_at_minute        0
dtype: int64

In [5]:
X=df.drop("i_impact",axis=1)


In [6]:
X.head()

number  incidentstate  active  reassignmentcount  reopencount  sysmodcount  \
0       0              7       1                  0            0            0   
1       0              1       1                  1            0            1   
2       0              1       1                  1            0            2   
3       0              1       1                  1            0            3   
4       0              1       1                  1            0            4   

   contact_type  knowledge  upriorityconfirmation  caller_id  ...  \
0             3          1                      0       2403  ...   
1             3          1                      0       2403  ...   
2             3          1                      0       2403  ...   
3             3          1                      0       2403  ...   
4             3          1                      0       2403  ...   

   opened_at_day  opened_at_month  opened_at_year  opened_at_hr  \
0             29                2            2016             4   
1             29                2            2016             4   
2             29                2            2016             4   
3             29                2            2016             4   
4             29                2            2016             4   

   opened_at_minute  created_at_day  created_at_month  created_at_year  \
0                40              29                 2             2016   
1                40              29                 2             2016   
2                40              29                 2             2016   
3                40              29                 2             2016   
4                40              29                 2             2016   

   created_at_hr  created_at_minute  
0              4                 57  
1              4                 57  
2              4                 57  
3              4                 57  
4              4                 57  

[5 rows x 32 columns]

In [7]:
Y = df['i_impact']

In [8]:
Y.head()

0    2
1    2
2    2
3    2
4    2
Name: i_impact, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=10)

In [11]:
from imblearn.over_sampling import SMOTE

In [12]:
smote = SMOTE()

In [13]:
X_train_smote, y_train_smote = smote.fit_resample(X_train.astype('float'), y_train)

In [14]:
from collections import Counter
print("Before SMOTE :",Counter(y_train))
print("After SMOTE :",Counter(y_train_smote))

Before SMOTE : Counter({2: 94155, 3: 2647, 1: 2393})
After SMOTE : Counter({2: 94155, 1: 94155, 3: 94155})


In [15]:
X_train_smote_new= X_train_smote[['caller_id','open_by','loc','category']]
X_test_new= X_test[['caller_id','open_by','loc','category']]

In [16]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(max_depth=27)
model_rf.fit(X_train_smote_new,y_train_smote)


RandomForestClassifier(max_depth=27)

In [17]:
# Predicting the model
y_predict_rf = model_rf.predict(X_test_new)

In [18]:
# Finding accuracy, precision, recall and confusion matrix
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test,y_predict_rf))
print(classification_report(y_test,y_predict_rf))


0.9788300049396655
              precision    recall  f1-score   support

           1       0.68      0.92      0.78      1098
           2       1.00      0.98      0.99     40176
           3       0.78      0.95      0.86      1239

    accuracy                           0.98     42513
   macro avg       0.82      0.95      0.88     42513
weighted avg       0.98      0.98      0.98     42513



In [19]:
confusion_matrix(y_test,y_predict_rf)


array([[ 1011,    74,    13],
       [  445, 39419,   312],
       [   24,    32,  1183]], dtype=int64)

In [56]:
accuracy_rf = (716+39962+1048)/(42513)*100

In [20]:
# Training the model
from sklearn.tree import DecisionTreeClassifier
model_dtree=DecisionTreeClassifier()
model_dtree.fit(X_train_smote_new,y_train_smote)

DecisionTreeClassifier()

In [21]:
# Predicting the model
y_predict_dtree = model_dtree.predict(X_test_new)

In [22]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_dtree))
print(classification_report(y_test,y_predict_dtree))

0.9781713828711218
              precision    recall  f1-score   support

           1       0.68      0.93      0.78      1098
           2       1.00      0.98      0.99     40176
           3       0.78      0.95      0.86      1239

    accuracy                           0.98     42513
   macro avg       0.82      0.95      0.88     42513
weighted avg       0.98      0.98      0.98     42513



In [23]:
confusion_matrix(y_test,y_predict_dtree )

array([[ 1021,    63,    14],
       [  470, 39389,   317],
       [   21,    43,  1175]], dtype=int64)

In [24]:
accuracy_dtree = (654+38955+1002)/(42513)*100

In [25]:
# Training the model
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=12,metric='euclidean') # Maximum accuracy for n=10


In [26]:
model_knn.fit(X_train_smote_new,y_train_smote)

KNeighborsClassifier(metric='euclidean', n_neighbors=12)

In [27]:
# Predicting the model
y_predict_knn = model_knn.predict(X_test_new)

In [28]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_knn))
print(classification_report(y_test,y_predict_knn))

0.894032413614659
              precision    recall  f1-score   support

           1       0.28      0.95      0.43      1098
           2       1.00      0.89      0.94     40176
           3       0.41      0.93      0.57      1239

    accuracy                           0.89     42513
   macro avg       0.56      0.92      0.65     42513
weighted avg       0.96      0.89      0.92     42513



In [29]:
confusion_matrix(y_test,y_predict_knn)

array([[ 1048,    34,    16],
       [ 2723, 35809,  1644],
       [   24,    64,  1151]], dtype=int64)

In [30]:
accuracy_knn = (950+33946+1083)/(42513)*100

In [31]:
# Training the model
from xgboost import XGBClassifier
model_xgb = XGBClassifier()


In [32]:
model_xgb.fit(X_train_smote_new,y_train_smote)

C:\Users\Anup w\anaconda3\lib\site-packages\xgboost\sklearn.py:892: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[12:08:10] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [33]:
# Predicting the model
y_predict_xgb = model_xgb.predict(X_test_new)

In [34]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_xgb))
print(classification_report(y_test,y_predict_xgb))

0.9174134970479618
              precision    recall  f1-score   support

           1       0.38      0.84      0.53      1098
           2       0.99      0.92      0.96     40176
           3       0.39      0.92      0.55      1239

    accuracy                           0.92     42513
   macro avg       0.59      0.89      0.68     42513
weighted avg       0.96      0.92      0.93     42513



In [35]:
confusion_matrix(y_test,y_predict_xgb)

array([[  918,   160,    20],
       [ 1451, 36946,  1779],
       [   30,    71,  1138]], dtype=int64)

In [36]:
accuracy_XGB= (471+39817+997)/(42513)*100

In [37]:
# Training the model
from sklearn.neural_network import MLPClassifier
model_mlp = MLPClassifier()

In [38]:
model_mlp.fit(X_train_smote_new,y_train_smote)

C:\Users\Anup w\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [39]:
# Predicting the model
y_predict_mlp = model_mlp.predict(X_test_new)

In [40]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_mlp))
print(classification_report(y_test,y_predict_mlp))

0.5877261073083527
              precision    recall  f1-score   support

           1       0.05      0.45      0.09      1098
           2       0.98      0.58      0.73     40176
           3       0.11      0.85      0.20      1239

    accuracy                           0.59     42513
   macro avg       0.38      0.63      0.34     42513
weighted avg       0.93      0.59      0.70     42513



In [41]:
confusion_matrix(y_test,y_predict_mlp)

array([[  490,   402,   206],
       [ 8628, 23446,  8102],
       [  109,    80,  1050]], dtype=int64)

In [42]:
accuracy_mlp = (670+28542+863)/(42513)*100

In [43]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [44]:
sgnb = GaussianNB()
smnb = MultinomialNB()

In [45]:
spred_gnb = sgnb.fit(X_train_smote_new,y_train_smote)

In [46]:
# Predicting the model
y_predict_sgnb = spred_gnb.predict(X_test_new)

In [47]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_sgnb))
print(classification_report(y_test,y_predict_sgnb))

0.5028109048996777
              precision    recall  f1-score   support

           1       0.03      0.27      0.06      1098
           2       0.97      0.51      0.66     40176
           3       0.06      0.63      0.11      1239

    accuracy                           0.50     42513
   macro avg       0.36      0.47      0.28     42513
weighted avg       0.92      0.50      0.63     42513



In [48]:
confusion_matrix(y_test,y_predict_sgnb )

array([[  291,   454,   353],
       [ 8560, 20306, 11310],
       [  302,   158,   779]], dtype=int64)

In [49]:
accuracy_gnb = (474+20378+575)/(42513)*100

In [50]:
spred_mnb = smnb.fit(X_train_smote_new,y_train_smote)

In [51]:
# Predicting the model
y_predict_smnb = spred_mnb.predict(X_test_new)

In [52]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_smnb))
print(classification_report(y_test,y_predict_smnb))

0.5192999788300049
              precision    recall  f1-score   support

           1       0.04      0.13      0.06      1098
           2       0.96      0.53      0.68     40176
           3       0.04      0.59      0.08      1239

    accuracy                           0.52     42513
   macro avg       0.35      0.42      0.28     42513
weighted avg       0.91      0.52      0.65     42513



In [53]:
confusion_matrix(y_test,y_predict_smnb)

array([[  147,   474,   477],
       [ 3272, 21194, 15710],
       [  115,   388,   736]], dtype=int64)

In [54]:
accuracy_mnb =(517+7708+708)/(42513)*100

In [57]:
data = {"MODEL":pd.Series(["model_rf","model_dtree","model_knn","model_xgb","model_mlp","spred_gnb ","spred_mnb"]),
        "Accuracy":pd.Series([accuracy_rf,accuracy_dtree,accuracy_knn,accuracy_XGB,accuracy_mlp,accuracy_gnb,accuracy_mnb])}
table=pd.DataFrame(data)
table 

MODEL   Accuracy
0     model_rf  98.148802
1  model_dtree  95.526074
2    model_knn  84.630584
3    model_xgb  97.111472
4    model_mlp  70.743067
5   spred_gnb   50.401054
6    spred_mnb  21.012396